apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: 386497974168.dkr.ecr.us-east-1.amazonaws.com/web:php
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/etc/nginx/html"
              name: php-storage
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
      imagePullSecrets:
        - name: ecr-secret
