apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: 891376930154.dkr.ecr.us-east-1.amazonaws.com/web:nginx3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: "/etc/nginx/html"
              name: php-storage
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc

