FROM debian:latest

RUN apt-get update -y && \
    apt-get install -y nginx && \
    mkdir -p /etc/nginx/conf.d /etc/ssl/private && \
    chmod 755 /etc/nginx/conf.d /etc/ssl/private

COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf
COPY certificado.crt /etc/ssl/certs/certificado.crt
COPY certificado.key /etc/ssl/private/certificado.key

CMD ["nginx", "-g", "daemon off;"]
