name: Deploy Docker Images to AWS

on:
  push:
    branches:
      - Ansible

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio
        uses: actions/checkout@v3

      - name: Configurar AWS credenciales
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1

      - name: Verificar autenticación con AWS
        run: aws sts get-caller-identity

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible docker.io

      - name: Ejecutar Ansible Playbook
        run: |
          ansible-playbook aws2_web/task/main.yml -i localhost, --connection=local

