name: Deploy Docker Images to AWS

on:
  push:
    branches:
      - Ansible
  workflow_dispatch:  # Esto habilita la ejecuci칩n manual del workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio
        uses: actions/checkout@v3
        with:
          ref: Ansible

      - name: Configurar AWS credenciales
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verificar autenticaci칩n con AWS
        run: aws sts get-caller-identity

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt remove -y containerd containerd.io  # Eliminar containerd si est치 presente
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh  # Instalar Docker usando el script oficial

      - name: Verificar instalaci칩n de Docker y Ansible
        run: |
          docker --version
          ansible --version

      - name: Verificar archivos en el repositorio
        run: |
          ls -l aws2_web/tasks/

      - name: Verificar archivos en templates
        run: |
          ls -l aws2_web/templates/


      - name: Ejecutar Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          ansible-playbook aws2_web/tasks/main.yml -i localhost, --connection=local



