name: Eliminar pods

on:
  push:
    branches:
      - Kubernetes
  workflow_dispatch: 

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Si viene de un push a Kubernetes, chequeará esa rama
          ref: ${{ github.ref_name }}
      
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - run: aws eks update-kubeconfig --name tecnoiliberis --region us-east-1

      - run: kubectl delete -f pod/ --ignore-not-found
