name: Lanzar YMLs

on:
  push:
    branches:
      - kubernetes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorios
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Modificar la configuración de EKS
        run: aws eks update-kubeconfig --name tecnoiliberis --region us-east-1

      - name: Aplicar Deployments
        run: kubectl apply -f pod/
