name: 3. Lanzar YMLs

on:
  push:
    branches:
      - Kubernetes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # Add this section to define permissions
      actions: read # Grant read permission for actions
      contents: read # Often needed for checkout and other operations
      # Add other permissions as needed, e.g., if you write to the repo:
      # contents: write

    steps:
      - name: Repositorios
        uses: actions/checkout@v4
        with:
          ref: Kubernetes

      - name: Listar artefactos disponibles
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --repo ${{ github.repository }}
          # You might not strictly need this step if you're only downloading
          # a known artifact. If you're trying to dynamically find artifacts,
          # then you need this.

      - name: Descargar artefacto EFS ID
        uses: actions/download-artifact@v4
        with:
          name: efs-id
          path: ./efs-artifact

      - name: Leer EFS ID
        id: read_efs
        run: |
          EFS_ID=$(cat ./efs-artifact/efs_id.txt)
          echo "EFS_ID=$EFS_ID" >> $GITHUB_ENV
          echo "efs_id=$EFS_ID" >> $GITHUB_OUTPUT

      - name: Mostrar EFS_ID para debug
        run: echo "EFS ID es ${{ env.EFS_ID }}"

      - name: Reemplazar volumeHandle
        run: |
          sed -i "s/fs-REEMPLAZAR-ID-EFS/${{ env.EFS_ID }}/g" pod/volumenes_efs.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:       ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:       ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:              us-east-1

      - name: Modificar la configuración de EKS
        run: aws eks update-kubeconfig --name tecnoiliberis --region us-east-1

      - name: Aplicar Deployments
        run: kubectl apply -f pod/
      - name: Modificar la configuración de EKS
        run: aws eks update-kubeconfig --name tecnoiliberis --region us-east-1

      - name: Aplicar Deployments
        run: kubectl apply -f pod/
