name: 2. Implementar Terraform a AWS

on:
  push:
    branches:
      - Terraform
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Inicializar Terraform
        run: terraform init -reconfigure
        working-directory: ./principal

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./principal
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_git_token: ${{ secrets.GIT_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./principal
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_git_token: ${{ secrets.GIT_TOKEN }}

      - name: Extraer id del EFS
        id: output
        run: |
          EFS_ID=$(terraform -chdir=prod output -raw efs_id)
          echo "EFS_ID=$EFS_ID" >> $GITHUB_ENV
          echo "$EFS_ID" > efs_id.txt

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: efs-id
          path: efs_id.txt
